### ISSUE TITLE
The request cannot be completed because you have exceeded your <a href=\"/youtube/v3/getting-started#quota\">quota

### ISSUE THREAD

**Issue by rcbalmera** [Stekeblad/Stekeblads-Video-Uploader#13]
Hello I want to share this issue today.
```
Here is the error details:
-----------------------------------------
403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "youtube.quota",
    "message" : "The request cannot be completed because you have exceeded your <a href=\"/youtube/v3/getting-started#quota\">quota</a>.",
    "reason" : "quotaExceeded"
  } ],
  "message" : "The request cannot be completed because you have exceeded your <a href=\"/youtube/v3/getting-started#quota\">quota</a>."
}
-----------------------------------------
com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "youtube.quota",
    "message" : "The request cannot be completed because you have exceeded your <a href=\"/youtube/v3/getting-started#quota\">quota</a>.",
    "reason" : "quotaExceeded"
  } ],
  "message" : "The request cannot be completed because you have exceeded your <a href=\"/youtube/v3/getting-started#quota\">quota</a>."
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:554)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:474)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:591)
	at io.github.stekeblad.videouploader.youtube.Uploader.upload(Uploader.java:283)
	at io.github.stekeblad.videouploader.youtube.Uploader.access$000(Uploader.java:39)
	at io.github.stekeblad.videouploader.youtube.Uploader$1.call(Uploader.java:147)
	at io.github.stekeblad.videouploader.youtube.Uploader$1.call(Uploader.java:134)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by Stekeblad** [comment]
Hi rcbalmera, when did this happen? From what I can see the program has not been even close to reaching the quota limit during the last 30 days.
