### ISSUE TITLE
After clicking "Apply preset"

### ISSUE THREAD

**Issue by aimbattt** [Stekeblad/Stekeblads-Video-Uploader#36]
![image](https://user-images.githubusercontent.com/77395389/131212174-38cde368-fc0c-4df3-a6b4-98da4aeb2ee2.png)

Sorry, something went wrong!
Here is the error details:
-----------------------------------------
null
-----------------------------------------
java.lang.NullPointerException
at io.github.stekeblad.videouploader.youtube.VideoInformationBase.verifyButtonExistence(VideoInformationBase.java:237)
at io.github.stekeblad.videouploader.youtube.VideoInformationBase.setButton1(VideoInformationBase.java:198)
at io.github.stekeblad.videouploader.utils.state.VideoUploadState.set(VideoUploadState.java:114)
at io.github.stekeblad.videouploader.utils.state.VideoUploadState.setLocked(VideoUploadState.java:57)
at io.github.stekeblad.videouploader.main.mainWindowController.onPresetApplicationSuccess(mainWindowController.java:848)
at io.github.stekeblad.videouploader.main.mainWindowController.lambda$null$6(mainWindowController.java:151)
at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
at java.security.AccessController.doPrivileged(Native Method)
at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
at java.lang.Thread.run(Unknown Source)

**Comment by Stekeblad** [comment]
Hi @aimbattt 

Do you think it can be something related to the video or the preset used that could have led to this? Is it something that happens every time even with a very different preset and other videos?

**Comment by aimbattt** [comment]
I tried to put different ones, it still does not work

**Comment by Stekeblad** [comment]
I can't figure out what can lead to a NullPointerException to happen at that location and I can not recreate it. I do see why it happen from your error message so I add a check and code to handle that, but I am afraid it may only result in new equally confusing errors appearing a few lines later... Let's hope for the best and its fixed.

**Comment by Stekeblad** [comment]
Version 1.4.6 is now out that hopefully fix this
