### ISSUE TITLE
Cannot upload or edit videos after applying preset

### ISSUE THREAD

**Issue by Chubby-Bub** [Stekeblad/Stekeblads-Video-Uploader#49]
Hello, I am experiencing the same problem as here: https://github.com/Stekeblad/Stekeblads-Video-Uploader/issues/21

I can upload videos fine if I edit them manually in the list, but if I apply a preset I can't edit, delete or upload them. If I press the buttons nothing happens, not even an error message.
This appears to possibly be because there is an extra "edit" button if I apply a preset. Take a look here
Normal (no preset applied):
![image](https://user-images.githubusercontent.com/65587508/140592523-2896b34b-73dc-4e8b-8136-c73756ffdded.png)
Does not work (preset applied):
![image](https://user-images.githubusercontent.com/65587508/140592553-9bca0c79-8c72-4bcf-b203-0e0f1df64efd.png)

The odd thing is that yesterday I uploaded videos and it worked fine, this started happening suddenly. I tried making a new preset and it still did not work.
Thanks.

**Comment by Chubby-Bub** [comment]
I just tried again and I got this message: 

```
Sorry, something went wrong!
Here is the error details:
-----------------------------------------
null
-----------------------------------------
java.lang.NullPointerException
	at io.github.stekeblad.videouploader.youtube.VideoInformationBase.getVideoName(VideoInformationBase.java:92)
	at io.github.stekeblad.videouploader.main.mainWindowController.onStartUpload(mainWindowController.java:720)
	at io.github.stekeblad.videouploader.utils.state.VideoUploadState.lambda$set$2(VideoUploadState.java:109)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3473)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3401)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3769)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3488)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1765)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2497)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:941)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Chubby-Bub** [comment]
Another update: The new preset I had made was cloned. I deleted it and manually made a new one, and it worked. This indicates to me that the bug was an issue with my preset, but what it was I don't know.

**Comment by Stekeblad** [comment]
Hi @Chubby-Bub 

I have been able to recreate the issue from your description, the buttons overlap each other when I used a cloned preset.

To get the error message I had to click on Start Upload, it is the same as in issue #48 

I have found that something breaks because it is a space in the preset name, I just removed it and the preset started to work, It does not have to be a cloned preset, adding a space to the name of an existing preset will make it stop working as well.

![image](https://user-images.githubusercontent.com/12627375/140601028-31f7a608-19bc-4783-896e-540fb2c5ec88.png)

When I find time I will try to find a solution to allow spaces in the name or alternatively add a check to prevent spaces.

**Comment by alikthe** [comment]
Dieser Fehler erscheint beim Herunterladen von Videos


Failed to upload the video "Онлайн профессия. [АКТУАЛЬНО НА 26.11.2021]"
Here is the error details:
-----------------------------------------
400 Bad Request
POST https://youtube.googleapis.com/upload/youtube/v3/videos?notifySubscribers=false&part=snippet&part=statistics&part=status&uploadType=resumable
{
  "code": 400,
  "errors": [
    {
      "domain": "youtube.video",
      "location": "body.snippet.description",
      "locationType": "other",
      "message": "The request metadata specifies an invalid video description.",
      "reason": "invalidDescription"
    }
  ],
  "message": "The request metadata specifies an invalid video description."
}
-----------------------------------------
com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
POST https://youtube.googleapis.com/upload/youtube/v3/videos?notifySubscribers=false&part=snippet&part=statistics&part=status&uploadType=resumable
{
  "code": 400,
  "errors": [
    {
      "domain": "youtube.video",
      "location": "body.snippet.description",
      "locationType": "other",
      "message": "The request metadata specifies an invalid video description.",
      "reason": "invalidDescription"
    }
  ],
  "message": "The request metadata specifies an invalid video description."
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:532)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at io.github.stekeblad.videouploader.youtube.Uploader.upload(Uploader.java:307)
	at io.github.stekeblad.videouploader.youtube.Uploader.access$000(Uploader.java:39)
	at io.github.stekeblad.videouploader.youtube.Uploader$1.call(Uploader.java:156)
	at io.github.stekeblad.videouploader.youtube.Uploader$1.call(Uploader.java:143)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Stekeblad** [comment]
Hi again @Chubby-Bub 

The error message returned from YouTube is:

> The authenticated user doesn't have permissions to upload and set custom video thumbnails.

By searching for that error message I have found out that [you can not set a custom thumbnail if your account is not verified](https://support.google.com/youtube/answer/72431). Your video appears to have been successfully uploaded (try view the videowith the same video id as in the error message)

See also https://www.youtube.com/verify
