### ISSUE TITLE
hey getting this error when uploading 

### ISSUE THREAD

**Issue by cChimney** [Stekeblad/Stekeblads-Video-Uploader#69]
Sorry, something went wrong!
Here is the error details:
-----------------------------------------
null
-----------------------------------------
java.lang.NullPointerException
	at io.github.stekeblad.videouploader.youtube.VideoInformationBase.getVideoName(VideoInformationBase.java:92)
	at io.github.stekeblad.videouploader.main.mainWindowController.onStartUpload(mainWindowController.java:720)
	at io.github.stekeblad.videouploader.utils.state.VideoUploadState.lambda$set$2(VideoUploadState.java:109)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3473)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3401)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3769)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3488)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1765)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2497)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:941)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Unknown Source)

**Comment by Stekeblad** [comment]
Hi @cChimney 
You may have the same error as in issue #49 ,can you try that solution?

> I have found that something breaks because it is a space in the preset name, I just removed it and the preset started to work, It does not have to be a cloned preset, adding a space to the name of an existing preset will make it stop working as well.

The quote mentions presets, not uploads, but the issue applies to uploads create from presets with space in their name.

**Comment by cChimney** [comment]
Thanks. getting new error now.

```
403 Forbidden
PUT https://youtube.googleapis.com/upload/youtube/v3/thumbnails/set?videoId=oXkbpg6ge9g&uploadType=resumable&upload_id=ADPycdvYpuoVhtAsmrRk1deOx2IiF_hGr9IqUKw3175WIHvzeAUTnt-VPl137lFGWotyQvIL7xMxfTGT_lGadamVfoU
{
  "code": 403,
  "errors": [
    {
      "domain": "youtube.thumbnail",
      "location": "Authorization",
      "locationType": "header",
      "message": "The authenticated user doesn't have permissions to upload and set custom video thumbnails.",
      "reason": "forbidden"
    }
  ],
  "message": "The authenticated user doesn't have permissions to upload and set custom video thumbnails."
}
-----------------------------------------
com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
PUT https://youtube.googleapis.com/upload/youtube/v3/thumbnails/set?videoId=oXkbpg6ge9g&uploadType=resumable&upload_id=ADPycdvYpuoVhtQhBnRk1deOx2IiF_hGr9IqUKw3175WIHvzeAUTnt-VPl137lFGWotyQvIL7xMxfTGT_lGadamVfoU
{
  "code": 403,
  "errors": [
    {
      "domain": "youtube.thumbnail",
      "location": "Authorization",
      "locationType": "header",
      "message": "The authenticated user doesn't have permissions to upload and set custom video thumbnails.",
      "reason": "forbidden"
    }
  ],
  "message": "The authenticated user doesn't have permissions to upload and set custom video thumbnails."
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:532)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at io.github.stekeblad.videouploader.youtube.Uploader.upload(Uploader.java:325)
	at io.github.stekeblad.videouploader.youtube.Uploader.access$000(Uploader.java:39)
	at io.github.stekeblad.videouploader.youtube.Uploader$1.call(Uploader.java:156)
	at io.github.stekeblad.videouploader.youtube.Uploader$1.call(Uploader.java:143)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by cChimney** [comment]
Without thumbnail it works fine

**Comment by Stekeblad** [comment]
You need to verify your channel before setting a custom thumbnail, see the issue I linked before for more details

**Comment by cChimney** [comment]
oh thanks. nice uploaders and good support <3

**Comment by cChimney** [comment]
btw is the upload limit per channel client side or does youtube block you?

**Comment by Stekeblad** [comment]
Stekeblad's Video Uploader does not apply a per-user or channel limit but there is a global daily limit shared by all users. YouTube may decide to block you based on usage patterns, algorithms or who knows what.

**Comment by cChimney** [comment]
> Stekeblad's Video Uploader does not apply a per-user or channel limit but there is a global daily limit shared by all users. YouTube may decide to block you based on usage patterns, algorithms or who knows what.

Alright, is it possible to just not choose a category?

**Comment by cChimney** [comment]
Lmao my account got suspended
